# Generated by Django 3.2.8 on 2021-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='workspace_id',
            new_name='workspace',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
