# Generated by Django 3.2.8 on 2021-11-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='priority',
            field=models.IntegerField(choices=[(1, 'very important'), (2, 'important'), (3, 'normal')], default=3),
        ),
    ]
