# Generated by Django 3.2.8 on 2021-11-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='priority',
            field=models.CharField(choices=[(1, 'very important'), (2, 'important'), (3, 'normal')], default=3, max_length=20),
        ),
    ]
