# Generated by Django 3.2.8 on 2021-11-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='priority',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
