# Generated by Django 3.2.8 on 2021-11-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20211105_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='priority',
            field=models.CharField(default='보통', max_length=10),
        ),
    ]
