# Generated by Django 3.2.8 on 2021-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20211107_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
