# Generated by Django 3.2.8 on 2021-11-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20211106_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='priority',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
